spring.application.name=backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://db_user:Tharaka123@cluster0.16ewnrh.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=smartcampus

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT Configuration
smartcampus.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
smartcampus.jwt.expiration=86400000
